# Problema2


Lea el archivo 'winemag-data-130k-v2.csv' y realice lo siguiente:

- Explore el dataframe según lo visto en clase
- Realice al menos  4 renombre de columna y 3 creación de nuevas columnas según criterio. Deberá crear las columnas que crea conveniente. 
    Ejemplo: Según el país etiquetelos según continente.

- Genere 4 reportes por agrupamiento de datos. Deberá elegir que reportes realizar
    - Ejemplo: Por contienente mostrar los vinos mejor puntuados
    - Ejemplo2: Promedio de precio de vino y cantidad de reviews obtenidos según pais. Ordenado de mejor a peor 


- Al menos uno de estos datos agrupados deberán ser almacenados en excel o csv
   
   Puede revisar esta solución https://stackoverflow.com/questions/25789264/pandas-dataframegroupby-export-to-excel



### Datos 

winemag-data-130k-v2.csv
- https://github.com/gdelgador/ProgramacionPython202401/blob/main/Modulo5/src/winemag-data-130k-v2.csv

País según continente:
- https://gist.githubusercontent.com/kintero/7d1db891401f56256c79/raw/a61f6d0dda82c3f04d2e6e76c3870552ef6cf0c6/paises.csv

In [80]:
import pandas as pd
df_wine = pd.read_csv("./data/winemag-data-130k-v2.csv")

In [81]:
#Visualización de la data
df_wine.head(5)

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [82]:
# EXPLORACIÓN DE LA DATA
#Visualicemos las 10 primeras filas
df_wine.head(10)

#Visualicemos las 10 últimas filas
df_wine.tail(10)

#Veamos el tipo de dato de cada columna
df_wine.dtypes

#Veamos cuales son los nombres de las columnas (variables)
df_wine.columns
#Resumen de mis variables
df_wine.describe()

# Veamos los países únicos
df_wine['country'].unique()

array(['Italy', 'Portugal', 'US', 'Spain', 'France', 'Germany',
       'Argentina', 'Chile', 'Australia', 'Austria', 'South Africa',
       'New Zealand', 'Israel', 'Hungary', 'Greece', 'Romania', 'Mexico',
       'Canada', nan, 'Turkey', 'Czech Republic', 'Slovenia',
       'Luxembourg', 'Croatia', 'Georgia', 'Uruguay', 'England',
       'Lebanon', 'Serbia', 'Brazil', 'Moldova', 'Morocco', 'Peru',
       'India', 'Bulgaria', 'Cyprus', 'Armenia', 'Switzerland',
       'Bosnia and Herzegovina', 'Ukraine', 'Slovakia', 'Macedonia'],
      dtype=object)

In [83]:
#Nombremos a la primera columna que no tiene nombre "Unnamed: 0"
df=df_wine.rename(columns={'Unnamed: 0':'nombre_relleno'})
df.head(1)
# más adelante eliminaremos esta columna

,nombre_relleno,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia

In [84]:
#Eliminamos esta columna porque no la usaremos
df=df.drop(['nombre_relleno'],axis=1)
df

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65494,France,Made from young vines from the Vaulorent porti...,Fourchaume Premier Cru,90,45.0,Burgundy,Chablis,NaN,Roger Voss,@vossroger,William Fèvre 2005 Fourchaume Premier Cru (Ch...,Chardonnay,William Fèvre
65495,Australia,"This is a big, fat, almost sweet-tasting Caber...",NaN,90,22.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,Tapestry 2005 Cabernet Sauvignon (McLaren Vale),Cabernet Sauvignon,Tapestry
65496,US,"Much improved over the unripe 2005, Fritz's 20...",Estate,90,20.0,California,Dry Creek Valley,Sonoma,NaN,NaN,Fritz 2006 Estate Sauvignon Blanc (Dry Creek V...,Sauvignon Blanc,Fritz
65497,US,This wine wears its 15.8% alcohol better than ...,Block 24,90,31.0,California,Napa Valley,Napa,NaN,NaN,Hendry 2004 Block 24 Primitivo (Napa Valley),Primitivo,Hendry
65498,Spain,"A unique take on Manzanilla Sherry, which is o...",Manzanilla,90,10.0,Andalucia,Jerez,NaN,Michael Schachner,@wineschach,Bodegas Dios Baco S.L. NV Manzanilla Sherry (J...,Sherry,Bodegas Dios Baco S.L.

In [36]:
#Cambiamos algunos nombres a nuestras columnas
df=df.rename(columns={'country':'pais','description':'descripcion','points':'puntos','price':'precio'})
df.head(1)

,pais,descripcion,designation,puntos,precio,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia

In [40]:
# Si el siguiente año todas las economías del mundo sufren una presión inflacionaria de 25%
#Cual sería el precio el siguiente año
df['precio_2025']=df['precio']*1.25
df

,pais,descripcion,designation,puntos,precio,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,precio_2025
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,NaN
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,18.75
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,17.50
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,16.25
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,81.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65494,France,Made from young vines from the Vaulorent porti...,Fourchaume Premier Cru,90,45.0,Burgundy,Chablis,NaN,Roger Voss,@vossroger,William Fèvre 2005 Fourchaume Premier Cru (Ch...,Chardonnay,William Fèvre,56.25
65495,Australia,"This is a big, fat, almost sweet-tasting Caber...",NaN,90,22.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,Tapestry 2005 Cabernet Sauvignon (McLaren Vale),Cabernet Sauvignon,Tapestry,27.50
65496,US,"Much improved over the unripe 2005, Fritz's 20...",Estate,90,20.0,California,Dry Creek Valley,Sonoma,NaN,NaN,Fritz 2006 Estate Sauvignon Blanc (Dry Creek V...,Sauvignon Blanc,Fritz,25.00
65497,US,This wine wears its 15.8% alcohol better than ...,Block 24,90,31.0,California,Napa Valley,Napa,NaN,NaN,Hendry 2004 Block 24 Primitivo (Napa Valley),Primitivo,Hendry,38.75
65498,Spain,"A unique take on Manzanilla Sherry, which is o...",Manzanilla,90,10.0,Andalucia,Jerez,NaN,Michael Schachner,@wineschach,Bodegas Dios Baco S.L. NV Manzanilla Sherry (J...,Sherry,Bodegas Dios Baco S.L.,12.50

In [42]:
#Definimos una función para determinar si el precio de un vino es :
#Precio económico
#Precio moderado
#precio caro
#precio muy caro
def etiqueta_precio(precio:float):
    if precio<100:
        return 'Precio económico'
    elif precio<600 and precio>=100:
        return 'Precio moderado'
    elif precio<1500 and precio>=600:
        return 'Precio caro'
    elif precio>=1500:
        return 'Precio muy caro'
etiqueta_precio(1200)

'Precio caro'

In [43]:
df['nivel_precio']=df['precio'].apply(etiqueta_precio)
df.head(2)

,pais,descripcion,designation,puntos,precio,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,precio_2025,nivel_precio
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,NaN,None
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,18.75,Precio económico

In [45]:
#Consideramos el siguiente diccionario
diccionario={
'Pais' : ['Morocco','South Africa','Argentina','Brazil','Canada','Chile','Mexico','Peru','Uruguay','US','India','Lebanon','Armenia','Austria','Bosnia and Herzegovina','Bulgaria','Croatia','Cyprus','Czech Republic','England','France','Georgia','Germany','Greece','Hungary','Israel','Italy','Luxembourg','Macedonia','Moldova','Portugal','Romania','Serbia','Slovakia','Slovenia','Spain','Switzerland','Turkey','Ukraine','Australia','New Zealand'],
'Continente':['Africa','Africa','América','América','América','América','América','América','América','América','Asia','Asia','Europa','Europa','Europa','Europa','Europa','Europa','Europa','Europa','Europa','Europa','Europa','Europa','Europa','Europa','Europa','Europa','Europa','Europa','Europa','Europa','Europa','Europa','Europa','Europa','Europa','Europa','Europa','Oceanía','Oceanía']
}
df_pais=pd.DataFrame(diccionario)
df_pais

                      Pais Continente
0                  Morocco     Africa
1             South Africa     Africa
2                Argentina    América
3                   Brazil    América
4                   Canada    América
5                    Chile    América
6                   Mexico    América
7                     Peru    América
8                  Uruguay    América
9                       US    América
10                   India       Asia
11                 Lebanon       Asia
12                 Armenia     Europa
13                 Austria     Europa
14  Bosnia and Herzegovina     Europa
15                Bulgaria     Europa
16                 Croatia     Europa
17                  Cyprus     Europa
18          Czech Republic     Europa
19                 England     Europa
20                  France     Europa
21                 Georgia     Europa
22                 Germany     Europa
23                  Greece     Europa
24                 Hungary     Europa
25                  Israel     Europa
26                   Italy     Europa
27              Luxembourg     Europa
28               Macedonia     Europa
29                 Moldova     Europa
30                Portugal     Europa
31                 Romania     Europa
32                  Serbia     Europa
33                Slovakia     Europa
34                Slovenia     Europa
35                   Spain     Europa
36             Switzerland     Europa
37                  Turkey     Europa
38                 Ukraine     Europa
39               Australia    Oceanía
40             New Zealand    Oceanía

In [47]:
df_merge=pd.merge(df,df_pais,left_on='pais',right_on="Pais")
df_merge

,pais,descripcion,designation,puntos,precio,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,precio_2025,nivel_precio,Pais,Continente
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,NaN,None,Italy,Europa
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,18.75,Precio económico,Portugal,Europa
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,17.50,Precio económico,US,América
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,16.25,Precio económico,US,América
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,81.25,Precio económico,US,América
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65462,France,Made from young vines from the Vaulorent porti...,Fourchaume Premier Cru,90,45.0,Burgundy,Chablis,NaN,Roger Voss,@vossroger,William Fèvre 2005 Fourchaume Premier Cru (Ch...,Chardonnay,William Fèvre,56.25,Precio económico,France,Europa
65463,Australia,"This is a big, fat, almost sweet-tasting Caber...",NaN,90,22.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,Tapestry 2005 Cabernet Sauvignon (McLaren Vale),Cabernet Sauvignon,Tapestry,27.50,Precio económico,Australia,Oceanía
65464,US,"Much improved over the unripe 2005, Fritz's 20...",Estate,90,20.0,California,Dry Creek Valley,Sonoma,NaN,NaN,Fritz 2006 Estate Sauvignon Blanc (Dry Creek V...,Sauvignon Blanc,Fritz,25.00,Precio económico,US,América
65465,US,This wine wears its 15.8% alcohol better than ...,Block 24,90,31.0,California,Napa Valley,Napa,NaN,NaN,Hendry 2004 Block 24 Primitivo (Napa Valley),Primitivo,Hendry,38.75,Precio económico,US,América
65466,Spain,"A unique take on Manzanilla Sherry, which is o...",Manzanilla,90,10.0,Andalucia,Jerez,NaN,Michael Schachner,@wineschach,Bodegas Dios Baco S.L. NV Manzanilla Sherry (J...,Sherry,Bodegas Dios Baco S.L.,12.50,Precio económico,Spain,Europa

In [56]:
#REPORTE 1
reporte1=df_merge.groupby('Continente')['puntos'].agg(['max'])
reporte1.sort_values(by=['max'],ascending=[False])

            max
Continente
América     100
Europa      100
Oceanía     100
Africa       95
Asia         93

In [65]:
#REPORTE 2
reporte2=df_merge.groupby('Pais').agg({'precio':'mean','puntos': 'sum'})
reporte2.sort_values(by=['puntos'],ascending=[False])

                           precio   puntos
Pais
US                      36.344889  2406689
France                  41.577949   993050
Italy                   39.739836   886107
Spain                   27.875925   297468
Portugal                25.647360   261142
Chile                   21.021544   195485
Argentina               23.604663   165302
Austria                 30.846774   147138
Australia               35.786701   104262
Germany                 40.592233    94389
South Africa            24.293478    64911
New Zealand             26.662906    64678
Israel                  31.508065    22841
Greece                  21.845188    21110
Canada                  35.575472     9635
Bulgaria                14.014706     5978
Romania                 13.731343     5797
Hungary                 50.819672     5455
Uruguay                 26.737705     5286
Croatia                 25.000000     3837
Turkey                  25.767442     3794
Slovenia                24.000000     3431
England                 51.636364     3285
Georgia                 18.270270     3240
Mexico                  26.677419     2665
Brazil                  23.185185     2615
Moldova                 17.900000     2613
Lebanon                 30.400000     1753
Morocco                 21.090909      975
Peru                    20.500000      672
Serbia                  25.000000      615
Macedonia               15.833333      529
Czech Republic          23.666667      521
Cyprus                  16.000000      518
Ukraine                  9.200000      414
India                   13.500000      363
Luxembourg              23.000000      353
Switzerland             97.000000      351
Armenia                 14.000000       87
Slovakia                16.000000       87
Bosnia and Herzegovina  13.000000       85

In [74]:
#REPORTE 3
#Reporte de la cantidad de vendedores de vino por país y continente
reporte3=df_merge.groupby(['Continente','Pais']).agg({'pais': 'count'})
reporte3.sort_values(by=['Continente','pais'],ascending=[True,False])

                                    pais
Continente Pais
Africa     South Africa              737
           Morocco                    11
América    US                      27177
           Chile                    2258
           Argentina                1907
           Canada                    108
           Uruguay                    61
           Brazil                     31
           Mexico                     31
           Peru                        8
Asia       Lebanon                    20
           India                       4
Europa     France                  11174
           Italy                   10005
           Spain                    3409
           Portugal                 2963
           Austria                  1635
           Germany                  1051
           Israel                    259
           Greece                    242
           Bulgaria                   68
           Romania                    67
           Hungary                    61
           Croatia                    44
           Turkey                     43
           Slovenia                   39
           Georgia                    37
           England                    36
           Moldova                    30
           Serbia                      7
           Cyprus                      6
           Czech Republic              6
           Macedonia                   6
           Ukraine                     5
           Luxembourg                  4
           Switzerland                 4
           Armenia                     1
           Bosnia and Herzegovina      1
           Slovakia                    1
Oceanía    Australia                1177
           New Zealand               733

In [79]:
#REPORTE 4
#Este reporte muestras el precio promedio y la cantidad de vendedores de vino por nivel de precio
reporte4=df_merge.groupby('nivel_precio').agg({'precio':'mean','pais': 'count'})
reporte4.sort_values(by=['precio'],ascending=[False])

                       precio   pais
nivel_precio
Precio muy caro   2133.333333      3
Precio caro        821.185185     27
Precio moderado    160.081095   1899
Precio económico    30.743868  58872

In [78]:
#Enviaremos a gerencia nuestro reporte 4
ruta="./data/ReporteparaGerencia.xlsx"
reporte4.to_excel(ruta, index=False)